[package]
name = "ubpf"
version = "0.2.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
thiserror = "2.0"
assembler = { version = "0.2.0", path = "../assembler" }